name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          dependencies/arkhelper dir2ark ./_ark ./_build/gen -n "patch_xbox" -e -v 6
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
          find . -name "*.be" -type f -delete
          find . -name "*.xmplr" -type f -delete
          find . -name "default_xenia.xex" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: DC1DX-Xbox
          path: _build
